#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

typedef enum {
    CONFIGURATION_SCREENLAYOUT_SIZE_MASK = 0x0f,
    CONFIGURATION_SCREENLAYOUT_SIZE_UNDEFINED = 0x00,
    CONFIGURATION_SCREENLAYOUT_SIZE_SMALL = 0x01,
    CONFIGURATION_SCREENLAYOUT_SIZE_NORMAL = 0x02,
    CONFIGURATION_SCREENLAYOUT_SIZE_LARGE = 0x03,
    CONFIGURATION_SCREENLAYOUT_SIZE_XLARGE = 0x04,
    CONFIGURATION_SCREENLAYOUT_LONG_MASK = 0x30,
    CONFIGURATION_SCREENLAYOUT_LONG_UNDEFINED = 0x00,
    CONFIGURATION_SCREENLAYOUT_LONG_NO = 0x10,
    CONFIGURATION_SCREENLAYOUT_LONG_YES = 0x30,
    CONFIGURATION_SCREENLAYOUT_LAYOUTDIR_MASK = 0xC0,
    CONFIGURATION_SCREENLAYOUT_LAYOUTDIR_SHIFT = 6,
    CONFIGURATION_SCREENLAYOUT_LAYOUTDIR_UNDEFINED = 0x00,
    CONFIGURATION_SCREENLAYOUT_LAYOUTDIR_LTR = 0x01 << CONFIGURATION_SCREENLAYOUT_LAYOUTDIR_SHIFT,
    CONFIGURATION_SCREENLAYOUT_LAYOUTDIR_RTL = 0x02 << CONFIGURATION_SCREENLAYOUT_LAYOUTDIR_SHIFT,
    CONFIGURATION_SCREENLAYOUT_ROUND_MASK = 0x300,
    CONFIGURATION_SCREENLAYOUT_ROUND_SHIFT = 8,
    CONFIGURATION_SCREENLAYOUT_ROUND_UNDEFINED = 0x00,
    CONFIGURATION_SCREENLAYOUT_ROUND_NO = 0x1 << CONFIGURATION_SCREENLAYOUT_ROUND_SHIFT,
    CONFIGURATION_SCREENLAYOUT_ROUND_YES = 0x2 << CONFIGURATION_SCREENLAYOUT_ROUND_SHIFT,
    CONFIGURATION_SCREENLAYOUT_UNDEFINED = CONFIGURATION_SCREENLAYOUT_SIZE_UNDEFINED | CONFIGURATION_SCREENLAYOUT_LONG_UNDEFINED | CONFIGURATION_SCREENLAYOUT_LAYOUTDIR_UNDEFINED | CONFIGURATION_SCREENLAYOUT_ROUND_UNDEFINED,
    CONFIGURATION_SCREENLAYOUT_COMPAT_NEEDED = 0x10000000,
    
    CONFIGURATION_FONT_WEIGHT_ADJUSTMENT_UNDEFINED = INT_MAX,
    
    CONFIGURATION_TOUCHSCREEN_UNDEFINED = 0,
    CONFIGURATION_TOUCHSCREEN_NOTOUCH = 1,
    CONFIGURATION_TOUCHSCREEN_STYLUS = 2,
    CONFIGURATION_TOUCHSCREEN_FINGER = 3,
    
    CONFIGURATION_KEYBOARD_UNDEFINED = 0,
    CONFIGURATION_KEYBOARD_NOKEYS = 1,
    CONFIGURATION_KEYBOARD_QWERTY = 2,
    CONFIGURATION_KEYBOARD_12KEY = 3,
    
    CONFIGURATION_KEYBOARDHIDDEN_UNDEFINED = 0,
    CONFIGURATION_KEYBOARDHIDDEN_NO = 1,
    CONFIGURATION_KEYBOARDHIDDEN_YES = 2,
    CONFIGURATION_KEYBOARDHIDDEN_SOFT = 3,
    
    CONFIGURATION_HARDKEYBOARDHIDDEN_UNDEFINED = 0,
    CONFIGURATION_HARDKEYBOARDHIDDEN_NO = 1,
    CONFIGURATION_HARDKEYBOARDHIDDEN_YES = 2,
    
    CONFIGURATION_NAVIGATION_UNDEFINED = 0,
    CONFIGURATION_NAVIGATION_NONAV = 1,
    CONFIGURATION_NAVIGATION_DPAD = 2,
    CONFIGURATION_NAVIGATION_TRACKBALL = 3,
    CONFIGURATION_NAVIGATION_WHEEL = 4,
    
    CONFIGURATION_NAVIGATIONHIDDEN_UNDEFINED = 0,
    CONFIGURATION_NAVIGATIONHIDDEN_NO = 1,
    CONFIGURATION_NAVIGATIONHIDDEN_YES = 2,
    
    CONFIGURATION_ORIENTATION_UNDEFINED = 0,
    CONFIGURATION_ORIENTATION_PORTRAIT = 1,
    CONFIGURATION_ORIENTATION_LANDSCAPE = 2,
    CONFIGURATION_ORIENTATION_SQUARE = 3,
    
    CONFIGURATION_UI_MODE_TYPE_MASK = 0x0f,
    CONFIGURATION_UI_MODE_TYPE_UNDEFINED = 0x00,
    CONFIGURATION_UI_MODE_TYPE_NORMAL = 0x01,
    CONFIGURATION_UI_MODE_TYPE_DESK = 0x02,
    CONFIGURATION_UI_MODE_TYPE_CAR = 0x03,
    CONFIGURATION_UI_MODE_TYPE_TELEVISION = 0x04,
    CONFIGURATION_UI_MODE_TYPE_APPLIANCE = 0x05,
    CONFIGURATION_UI_MODE_TYPE_WATCH = 0x06,
    CONFIGURATION_UI_MODE_TYPE_VR_HEADSET = 0x07,
    CONFIGURATION_UI_MODE_NIGHT_MASK = 0x30,
    CONFIGURATION_UI_MODE_NIGHT_UNDEFINED = 0x00,
    CONFIGURATION_UI_MODE_NIGHT_NO = 0x10,
    CONFIGURATION_UI_MODE_NIGHT_YES = 0x20,
    
    CONFIGURATION_SCREEN_WIDTH_DP_UNDEFINED = 0,
    
    CONFIGURATION_SCREEN_HEIGHT_DP_UNDEFINED = 0,
    
    CONFIGURATION_SMALLEST_SCREEN_WIDTH_DP_UNDEFINED = 0,
    
    CONFIGURATION_DENSITY_DPI_UNDEFINED = 0,
    CONFIGURATION_DENSITY_DPI_ANY = 0xfffe,
    CONFIGURATION_DENSITY_DPI_NONE = 0xffff,
} ConfigurationVariables;

typedef enum {
    ACTIVITY_INFO_CONFIG_MCC = 0x0001,
    ACTIVITY_INFO_CONFIG_MNC = 0x0002,
    ACTIVITY_INFO_CONFIG_LOCALE = 0x0004,
    ACTIVITY_INFO_CONFIG_TOUCHSCREEN = 0x0008,
    ACTIVITY_INFO_CONFIG_KEYBOARD = 0x0010,
    ACTIVITY_INFO_CONFIG_KEYBOARD_HIDDEN = 0x0020,
    ACTIVITY_INFO_CONFIG_NAVIGATION = 0x0040,
    ACTIVITY_INFO_CONFIG_ORIENTATION = 0x0080,
    ACTIVITY_INFO_CONFIG_SCREEN_LAYOUT = 0x0100,
    ACTIVITY_INFO_CONFIG_UI_MODE = 0x0200,
    ACTIVITY_INFO_CONFIG_SCREEN_SIZE = 0x0400,
    ACTIVITY_INFO_CONFIG_SMALLEST_SCREEN_SIZE = 0x0800,
    ACTIVITY_INFO_CONFIG_DENSITY = 0x1000,
    ACTIVITY_INFO_CONFIG_LAYOUT_DIRECTION = 0x2000,
    ACTIVITY_INFO_CONFIG_COLOR_MODE = 0x4000,
    ACTIVITY_INFO_CONFIG_GRAMMATICAL_GENDER = 0x8000,
    ACTIVITY_INFO_CONFIG_ASSETS_PATHS = 0x80000000,
    ACTIVITY_INFO_CONFIG_FONT_SCALE = 0x40000000,
    ACTIVITY_INFO_CONFIG_WINDOW_CONFIGURATION = 0x20000000,
    ACTIVITY_INFO_CONFIG_FONT_WEIGHT_ADJUSTMENT = 0x10000000,
} ActivityInfoVariables;

@interface Configuration : NSObject

+(Configuration*)configurationFromTraitCollection:(UITraitCollection*)traitCollection;
+(int)reduceScreenLayout:(int)curLayout :(int)longSizeDp :(int)shortSizeDp;
-(BOOL)isLayoutSizeAtLeast:(int)size;
-(instancetype)init;
-(instancetype)initWithConfiguration:(Configuration*)o;
-(void)setTo:(Configuration*) o;
-(void)setToDefaults;
-(void)unset;
-(int)updateFrom:(Configuration*)delta;
-(void)setTo:(Configuration*)delta :(int) mask :(int)windowMask;
-(int)diff:(Configuration*) delta;
-(int)diffPublicOnly:(Configuration*) delta;
-(int)diff:(Configuration*)delta :(BOOL)compareUndefined :(BOOL)publicOnly;
+(BOOL)needNewResources:(int)configChanges :(int)interestingChanges;
-(BOOL)isNightModeActive;
-(NSArray*)getLocales;
-(void)setLocales:(NSArray *)locales;
-(void)setLocale:(NSLocale*)loc;
-(void)clearLocales;
-(int)getLayoutDirection;
-(void)setLayoutDirection:(NSLocale*)loc;
+(int)getScreenLayoutNoDirection:(int)screenLayout;
-(BOOL)isScreenRound;
+(Configuration*) generateDelta:(Configuration*)base :(Configuration*)change;

@property (nonatomic) float fontScale;
@property (nonatomic, retain) NSLocale *locale;
@property (nonatomic) int screenLayout;
@property (nonatomic) int fontWeightAdjustment;
@property (nonatomic) int touchscreen;
@property (nonatomic) int keyboard;
@property (nonatomic) int keyboardHidden;
@property (nonatomic) int hardKeyboardHidden;
@property (nonatomic) int navigation;
@property (nonatomic) int navigationHidden;
@property (nonatomic) int orientation;
@property (nonatomic) int uiMode;
@property (nonatomic) int screenWidthDp;
@property (nonatomic) int screenHeightDp;
@property (nonatomic) int smallestScreenWidthDp;
@property (nonatomic) int densityDpi;
@property (nonatomic, retain) NSArray *mLocaleList;
@property (nonatomic) BOOL userSetLocale;

@end
